Kagre preserve working path on impersonate
claudiospizzi/SecurityFever pull request #3
Opened 2020-12-29 21:08 UTC by Kagre

Take a look, this is a breaking change, but hopefully for the better.

The idea here was to remain in the current on the same working path as long as the new context still had access to it.

Also, if you don't add it in; please at least fix the assumption that when you pop the context back from admin the original user has access to wherever admin wandered off to...

2020-12-30 00:18 UTC, Kagre commented
This branch may now try to fix too much. I was hoping to eliminate the build failure, but now the issue is probably that the version imported is older than the one being built... still it's not a compiler probably shouldn't be using it to build itself.

2021-02-07 00:08 UTC, claudiospizzi commented
@Kagre 
Thank you for your PR - absolutely valid to have a consistent location. Can you check my comments?

2021-02-08 19:04 UTC, Kagre commented
Sorry, I'm still not super familiar with git/hub... where might I find these comments?

2021-02-08 19:34 UTC, claudiospizzi requested changes

2021-02-08 19:34 UTC, claudiospizzi commented on .build.ps1
> -$IBHConfig.RepositoryTask.Token = Use-VaultSecureString -TargetName 'GitHub Token (claudiospizzi)'
Yes this is breaking the build script as the module requires do be released before it's actually used.

2021-02-08 19:34 UTC, claudiospizzi commented on SecurityFever/Functions/Impersonation/Push-ImpersonationContext.ps1
> +    try
Not sure what your goal is with this try/catch/finally and the EAP manupulation - why not just use a `Test-Path` on the $OldPath, and catching the exception (of type UnauthorizedAccessException)?

2021-02-08 19:34 UTC, claudiospizzi commented on SecurityFever/Functions/Vault/Use-VaultSecureString.ps1
> +        $NonInteractive
Idea is good: I will implement this in a dedicated change also including the `Use-VaultCredential` which has the same behavior. Also I consider throwing a warning if we were not able to retrieve the credentials in non interactive mode. Should be find for the build system.

2021-02-08 19:35 UTC, claudiospizzi commented
@Kagre My bad, didn't submit the review. Should now be visible in this pr.

2021-02-17 23:21 UTC, Kagre commented on .build.ps1
> -$IBHConfig.RepositoryTask.Token = Use-VaultSecureString -TargetName 'GitHub Token (claudiospizzi)'
Do I need to figure out how to back these two out of the pr?

2026-06-18 20:49 UTC, claudiospizzi commented
Closed as inactive and stale.

2026-06-18 20:49 UTC, closed without merging